name: Cypress Shopping Card Regression
on:
    # trigger workflow manually
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci && cd cypress && npm ci
      - name: Run app and run tests
        run: npm run e2e:ci
