name: Cypress Shopping Card Regression
on:
    # trigger workflow manually
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
        npm ci && 
        npm run build && 
        cd Tests && 
        npm ci && 
        cd .. &&
        npm run start &
        sleep 5 &&
        curl http://localhost:3000 -I

      - name: Run tests
        run: npm run cy:run
