name: Cypress Shopping Card Regression
on:
    # trigger workflow manually
    workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
          npm ci && 
          npm run build && 
          cd Tests && 
          npm ci && 
          cd .. &&
          npm run start-server-build

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run tests
        run: npm run cy:run
