name: Cypress Shopping Card Regression
on:
    # trigger workflow manually
    workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
          npm ci && 
          npm run build && 
          cd Tests && 
          npm ci && 
          cd ../
      - name: Run server
        run: npm run start
      - name: Run Tests
          if:always()
          run: npm run cy:run
