name: Cypress Api Testing Regression
on:
  workflow_dispatch: null
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
          cd Tests && 
          npm install
      - name: Run API Tests
        run: npm run cy:api
