name: Cypress Shopping Card Regression
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Build the stack
        run: docker-compose up -f Tests/docker-compose.yml
