name: Cypress Api Testing Regression
on:
  workflow_dispatch: null
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
          npm ci && 
          npm run build && 
          cd Tests && 
          npm ci &&
          cd ../
      - name: Run API Tests
        run: |
          cd Tests  &&
          "npx cypress run --spec cypress/e2e/api-testing.cy.js --config baseUrl=https://petstore.swagger.io/"
