name: Cypress Shopping Card Regression
on:
    # trigger workflow manually
    workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install
        run: |
          npm ci && 
          npm run build && 
          cd Tests && 
          npm ci && 
          cd .. &&
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run server
        run: |
          npm run start
          echo ::set-output name=exit_code::$?
  job3:
    runs-on: ubuntu-latest
    if: always()
    needs: [job1, job2]
    steps:
      - name: Run tests
        run: npm run cy:run
