name: Cypress Shopping Card Regression 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build the stack
      - run: docker-compose up -f Tests/docker-compose.yml
